name: Release

on:
  release:
    types:
      - created

env:
  BUILD_TYPE: release

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup premake
      uses: abel0b/setup-premake@v1

    - name: Install required packages
      run: sudo apt-get install build-essential libglfw3-dev libglew-dev pkg-config

    - name: Premake
      run: premake5 gmake

    - name: Make
      run: cd build && make edge-surf-game

    - name: Move files
      run: mkdir edge-surf-game && mv assets build/edge-surf-game edge-surf-game/

    - name: Create zip file
      run: tar zcvf edge-surf-game-linux.tar.gz edge-surf-game/*

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: edge-surf-game-linux.tar.gz
        asset_name: edge-surf-game-linux.tar.gz
        tag: ${{ github.ref }}

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup premake
      uses: abel0b/setup-premake@v1

    - name: Premake
      run: premake5 vs2019

    - name: Install required packages
      run: vcpkg install glfw3:x86-windows-static glew:x86-windows-static glfw3:x64-windows-static glew:x64-windows-static && vcpkg integrate install

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      run: MSBuild.exe build\edge-surf-game.sln /t:Rebuild /p:Configuration=Release /p:Platform=Win32

    - name: Move files
      run: mkdir edge-surf-game && move /Y assets edge-surf-game && move build\edge-surf-game.exe edge-surf-game

    - name: Create zip file
      run: tar -a -c -f edge-surf-game-windows-x86.zip edge-surf-game

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: edge-surf-game-windows-x86.zip
        asset_name: edge-surf-game-windows-x86.zip
        tag: ${{ github.ref }}

    - name: Build
      run: MSBuild.exe build\edge-surf-game.sln /t:Rebuild /p:Configuration=Release /p:Platform=x64

    - name: Move files
      run: del edge-surf-game\edge-surf-game.exe && move build\edge-surf-game.exe edge-surf-game

    - name: Create zip file
      run: tar -a -c -f edge-surf-game-windows-x64.zip edge-surf-game

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: edge-surf-game-windows-x64.zip
        asset_name: edge-surf-game-windows-x64.zip
        tag: ${{ github.ref }}
